### PR TITLE
add tap on overlay to close

### PR DESCRIPTION
**Pull request by gorangajic**
When clicked on overlay close the drawer

### CODE REVIEW

**Comment by gorangajic** [comment]
btw this only works when `type="overlay"` because that `mainOverlay` is displayed only when type is overlay. Not sure why is that ?

**Comment by rt2zz** [comment]
in displace and static often times we do not want an overlay because it blocks touches

my concern with the PR is adding yet another prop. Is there some reason tapToClose cannot work for you? The only difference I see is there is a potential for dissonance between panCloseMask and openDrawerOffset. If this is the problem, perhaps we need a setting for panCloseMask to make it equal openDrawerOffset...

**Comment by gorangajic** [comment]
nvm ignore this :smile:

**Comment by rt2zz** [comment]
ah, I forgot to mention in v2 `panCloseMask` defaults to the size of the openDrawerOffset :+1: 

Thanks for the idea

**Pull request closed without merging**
