### PR TITLE
fix to work with React 16.0

### PR DESCRIPTION
**Pull request by sean-macfarlane**
Changed PropTypes it use the correct package `import PropTypes from 'prop-types';`
Works with React 16.0

### CODE REVIEW

**Comment by sean-macfarlane** [comment]
@rt2zz

**Comment by rt2zz** [comment]
@sean-macfarlane thanks, I believe prop-types needs to be added to package.json as well?

**Comment by jnbt** [comment]
@sean-macfarlane May you add the following change to `package.json` to your PR:

```
"dependencies": {
  "tween-functions": "^1.0.1"
  "prop-types": "^15.5.8"
}
```

**Comment by sean-macfarlane** [comment]
sorry about the delay, I have added the dependency as requested.

**Comment by altagir** [comment]
when is  this committed? is the main repo dead?
alternatively how to use your branch?
thanks

**Comment by sean-macfarlane** [comment]
@altagir if you can't wait for the PR to be merged, and want to use my branch, you can do so by changing your package.json to use my branch:
```
"dependencies": {
   "react-native-drawer": "git+https://github.com/sean-macfarlane/react-native-drawer.git",
}
```

or install the package by doing `npm install https://github.com/sean-macfarlane/react-native-drawer.git`

**Comment by sebandres** [comment]
@rt2zz Thanks for merging! 

Any chance of publishing a 2.3.1 or 2.4.0 with this change?

Cheers!

**Pull request merged**
