### PR TITLE
Added support for drawers opening from the top or bottom of the screen.

### PR DESCRIPTION
**Pull request by ericpalakovichcarr**
This primarily adds support for specifying `top` or `bottom` in addition to the existing `left` and `right` options for the `side` prop.  Here's a rundown of what's changed:
- In the library itself:
  - Variables like `left` have become a more generic version, like `length`
  - Added the `isLeftOrRightSide()` function, returning `true` if the drawer opens to the left or right side of the screen.  Otherwise it opens `top` or `bottom`.  It's used for things like determining which way the drawer should animate open, or whether to use `gestureState.dx` or `gestureState.dy` for example.
  - Added the `getDeviceLength()` function to be used in place of `this.state.viewport.width` (since `top` or `bottom` would need to use `this.state.viewport.height` instead)
  - Added the `getGestureDelta(gestureState)` function to be used in place of `gestureState.dx` (since `top` or `bottom` would need to use `gestureState.dy`)
- Updated README with the new `top` and `bottom` options for `side`
- Removed the `.idea` folder from the repository (let me know if this is a bridge too far)
- Updated the RNDrawerDemo project for the new `top` and `bottom` options.

Let me know if this needs anything else before it can be merged.

### CODE REVIEW

**Comment by dotansimha** [comment]
👍 
any news on merging this PR?

**Comment by dotansimha** [comment]
@bigsassy, just tested this PR in my project - it works great!! thanks!!

**Comment by ericpalakovichcarr** [comment]
@dotansimha You are very welcome 👍

**Comment by timkendall** [comment]
This is spicy. Thanks for implementing - exactly what I need!

**Comment by mikearche** [comment]
Awesome work, would love for this to get merged!

**Comment by michaelkirschbaum** [comment]
Tested this. Looks good 👍

**Comment by rt2zz** [comment]
this is fantastic, sorry for taking so long 👍  in we go :)

**Pull request merged**
